#!/usr/bin/env node
// build.js — bundle the data layer into the deployable single-file app,
// then generate SEO content pages, sitemap.xml, llms.txt, and robots.txt.
//
//   node build.js           full build (SPA + SEO pages + sitemaps)
//   node build.js --bundle  SPA bundle only (no SEO pages)
//   node build.js --seo     SEO pages only (no SPA bundle)

'use strict';

const fs   = require('fs');
const path = require('path');

const root = __dirname;
const read = (p) => fs.readFileSync(path.join(root, p), 'utf8');

function bundle() {
  const template  = read('index.template.html');
  const cities    = JSON.parse(read('cities.json'));
  const cmap      = JSON.parse(read('cmap.json'));
  const categories = JSON.parse(read('categories.json'));

  const mtKey = (process.env.MAPTILER_KEY ||
    (fs.existsSync(path.join(root, 'maptiler.key')) ? read('maptiler.key') : '')).trim();

  for (const ph of ['/*__CITIES__*/{}', '/*__CMAP__*/[]', '/*__CATEGORIES__*/{}', '/*__ROOT_JSONLD__*/']) {
    if (!template.includes(ph)) throw new Error('index.template.html is missing placeholder ' + ph);
  }

  const buildDate = (process.env.BUILD_DATE || new Date().toISOString().slice(0, 10));

  // Root JSON-LD (Dataset + WebSite) — generated by seo_pages.js and read back here.
  const rootJsonLdPath = path.join(root, 'seo', 'root-jsonld.json');
  const rootJsonLd = fs.existsSync(rootJsonLdPath)
    ? `<script type="application/ld+json">${read('seo/root-jsonld.json')}</script>`
    : '';

  const base = template
    .replace('/*__CITIES__*/{}', JSON.stringify(cities))
    .replace('/*__CMAP__*/[]', JSON.stringify(cmap))
    .replace('/*__CATEGORIES__*/{}', JSON.stringify(categories))
    .replace('/*__ROOT_JSONLD__*/', rootJsonLd)
    .replace('__MAPTILER_KEY__', mtKey)
    .replace(/__BUILD_DATE__/g, buildDate)
    .replace(/__BUILD_YEAR__/g, buildDate.slice(0, 4));

  const SITE = 'https://latamcrimemap.com';
  const attr = s => String(s).replace(/&/g, '&amp;').replace(/"/g, '&quot;').replace(/</g, '&lt;').replace(/>/g, '&gt;');
  const fillMeta = (html, m) => html
    .replace(/__PAGE_TITLE__/g, attr(m.title)).replace(/__OG_TITLE__/g, attr(m.title))
    .replace(/__OG_DESC__/g, attr(m.desc)).replace(/__OG_URL__/g, m.url).replace(/__OG_IMAGE__/g, m.image);

  const genericDesc = `Neighbourhood and city safety across Latin America — ${Object.keys(cities).length} cities on a green-to-red scale, synthesized from multiple safety sources.`;
  const generic = fillMeta(base, { title: 'Latam Crime Map', desc: genericDesc, url: SITE + '/', image: SITE + '/og-image.png' });
  fs.writeFileSync(path.join(root, 'index.html'), generic);
  fs.writeFileSync(path.join(root, '404.html'), generic);

  const keys = Object.keys(cities);
  console.log(`Built index.html (+404.html): ${generic.length} bytes  (${keys.length} cities, ${cmap.length} cmap stops)`);
}

function seoStage() {
  // seo_pages.js generates city content pages + method/ + sitemap.xml + llms.txt
  const { execFileSync } = require('child_process');
  execFileSync(process.execPath, [path.join(root, 'scripts', 'seo_pages.js')], { stdio: 'inherit' });
}

function fetchStage() {
  console.log('[fetch]  no-op — cities already fetched into cities.json.');
}
function scoreStage() {
  console.log('[score]  no-op — scores already baked into cities.json.');
}

const arg = process.argv[2] || '--all';
if (arg === '--bundle') {
  bundle();
} else if (arg === '--seo') {
  seoStage();
} else {
  fetchStage();
  scoreStage();
  // SEO pages first so root-jsonld.json exists before bundle reads it
  seoStage();
  bundle();
}
